#define DISABLE_RA0_ANALOG() _ANSA0 = 1
#define ENABLE_RA0_ANALOG() _ANSA0 = 0
#define CONFIG_AN0_AS_ANALOG() _ANSA0 = 0
#define CONFIG_AN0_AS_DIGITAL() _ANSA0 = 1
#define DISABLE_RA1_ANALOG() _ANSA1 = 1
#define ENABLE_RA1_ANALOG() _ANSA1 = 0
#define CONFIG_AN1_AS_ANALOG() _ANSA1 = 0
#define CONFIG_AN1_AS_DIGITAL() _ANSA1 = 1
#define DISABLE_RA11_ANALOG() _ANSA11 = 1
#define ENABLE_RA11_ANALOG() _ANSA11 = 0
#define CONFIG_AN9_AS_ANALOG() _ANSA11 = 0
#define CONFIG_AN9_AS_DIGITAL() _ANSA11 = 1
#define DISABLE_RA12_ANALOG() _ANSA12 = 1
#define ENABLE_RA12_ANALOG() _ANSA12 = 0
#define CONFIG_AN10_AS_ANALOG() _ANSA12 = 0
#define CONFIG_AN10_AS_DIGITAL() _ANSA12 = 1
#define DISABLE_RB0_ANALOG() _ANSB0 = 1
#define ENABLE_RB0_ANALOG() _ANSB0 = 0
#define CONFIG_AN2_AS_ANALOG() _ANSB0 = 0
#define CONFIG_AN2_AS_DIGITAL() _ANSB0 = 1
#define DISABLE_RB1_ANALOG() _ANSB1 = 1
#define ENABLE_RB1_ANALOG() _ANSB1 = 0
#define CONFIG_AN3_AS_ANALOG() _ANSB1 = 0
#define CONFIG_AN3_AS_DIGITAL() _ANSB1 = 1
#define DISABLE_RB2_ANALOG() _ANSB2 = 1
#define ENABLE_RB2_ANALOG() _ANSB2 = 0
#define CONFIG_AN4_AS_ANALOG() _ANSB2 = 0
#define CONFIG_AN4_AS_DIGITAL() _ANSB2 = 1
#define DISABLE_RB3_ANALOG() _ANSB3 = 1
#define ENABLE_RB3_ANALOG() _ANSB3 = 0
#define CONFIG_AN5_AS_ANALOG() _ANSB3 = 0
#define CONFIG_AN5_AS_DIGITAL() _ANSB3 = 1
#define DISABLE_RC0_ANALOG() _ANSC0 = 1
#define ENABLE_RC0_ANALOG() _ANSC0 = 0
#define CONFIG_AN6_AS_ANALOG() _ANSC0 = 0
#define CONFIG_AN6_AS_DIGITAL() _ANSC0 = 1
#define DISABLE_RC1_ANALOG() _ANSC1 = 1
#define ENABLE_RC1_ANALOG() _ANSC1 = 0
#define CONFIG_AN7_AS_ANALOG() _ANSC1 = 0
#define CONFIG_AN7_AS_DIGITAL() _ANSC1 = 1
#define DISABLE_RC2_ANALOG() _ANSC2 = 1
#define ENABLE_RC2_ANALOG() _ANSC2 = 0
#define CONFIG_AN8_AS_ANALOG() _ANSC2 = 0
#define CONFIG_AN8_AS_DIGITAL() _ANSC2 = 1
#define DISABLE_RC11_ANALOG() _ANSC11 = 1
#define ENABLE_RC11_ANALOG() _ANSC11 = 0
#define CONFIG_AN11_AS_ANALOG() _ANSC11 = 0
#define CONFIG_AN11_AS_DIGITAL() _ANSC11 = 1
#define DISABLE_RE12_ANALOG() _ANSE12 = 1
#define ENABLE_RE12_ANALOG() _ANSE12 = 0
#define CONFIG_AN12_AS_ANALOG() _ANSE12 = 0
#define CONFIG_AN12_AS_DIGITAL() _ANSE12 = 1
#define DISABLE_RE13_ANALOG() _ANSE13 = 1
#define ENABLE_RE13_ANALOG() _ANSE13 = 0
#define CONFIG_AN13_AS_ANALOG() _ANSE13 = 0
#define CONFIG_AN13_AS_DIGITAL() _ANSE13 = 1
#define DISABLE_RE14_ANALOG() _ANSE14 = 1
#define ENABLE_RE14_ANALOG() _ANSE14 = 0
#define CONFIG_AN14_AS_ANALOG() _ANSE14 = 0
#define CONFIG_AN14_AS_DIGITAL() _ANSE14 = 1
#define DISABLE_RE15_ANALOG() _ANSE15 = 1
#define ENABLE_RE15_ANALOG() _ANSE15 = 0
#define CONFIG_AN15_AS_ANALOG() _ANSE15 = 0
#define CONFIG_AN15_AS_DIGITAL() _ANSE15 = 1
#define ENABLE_RA0_OPENDRAIN() _ODCA0 = 1
#define DISABLE_RA0_OPENDRAIN() _ODCA0 = 0
#define ENABLE_RA1_OPENDRAIN() _ODCA1 = 1
#define DISABLE_RA1_OPENDRAIN() _ODCA1 = 0
#define ENABLE_RA4_OPENDRAIN() _ODCA4 = 1
#define DISABLE_RA4_OPENDRAIN() _ODCA4 = 0
#define ENABLE_RA8_OPENDRAIN() _ODCA8 = 1
#define DISABLE_RA8_OPENDRAIN() _ODCA8 = 0
#define ENABLE_RA9_OPENDRAIN() _ODCA9 = 1
#define DISABLE_RA9_OPENDRAIN() _ODCA9 = 0
#define ENABLE_RA10_OPENDRAIN() _ODCA10 = 1
#define DISABLE_RA10_OPENDRAIN() _ODCA10 = 0
#define ENABLE_RA11_OPENDRAIN() _ODCA11 = 1
#define DISABLE_RA11_OPENDRAIN() _ODCA11 = 0
#define ENABLE_RA12_OPENDRAIN() _ODCA12 = 1
#define DISABLE_RA12_OPENDRAIN() _ODCA12 = 0
#define ENABLE_RB0_OPENDRAIN() _ODCB0 = 1
#define DISABLE_RB0_OPENDRAIN() _ODCB0 = 0
#define ENABLE_RB1_OPENDRAIN() _ODCB1 = 1
#define DISABLE_RB1_OPENDRAIN() _ODCB1 = 0
#define ENABLE_RB2_OPENDRAIN() _ODCB2 = 1
#define DISABLE_RB2_OPENDRAIN() _ODCB2 = 0
#define ENABLE_RB3_OPENDRAIN() _ODCB3 = 1
#define DISABLE_RB3_OPENDRAIN() _ODCB3 = 0
#define ENABLE_RB4_OPENDRAIN() _ODCB4 = 1
#define DISABLE_RB4_OPENDRAIN() _ODCB4 = 0
#define ENABLE_RB5_OPENDRAIN() _ODCB5 = 1
#define DISABLE_RB5_OPENDRAIN() _ODCB5 = 0
#define ENABLE_RB6_OPENDRAIN() _ODCB6 = 1
#define DISABLE_RB6_OPENDRAIN() _ODCB6 = 0
#define ENABLE_RB7_OPENDRAIN() _ODCB7 = 1
#define DISABLE_RB7_OPENDRAIN() _ODCB7 = 0
#define ENABLE_RB8_OPENDRAIN() _ODCB8 = 1
#define DISABLE_RB8_OPENDRAIN() _ODCB8 = 0
#define ENABLE_RB9_OPENDRAIN() _ODCB9 = 1
#define DISABLE_RB9_OPENDRAIN() _ODCB9 = 0
#define ENABLE_RB10_OPENDRAIN() _ODCB10 = 1
#define DISABLE_RB10_OPENDRAIN() _ODCB10 = 0
#define ENABLE_RB11_OPENDRAIN() _ODCB11 = 1
#define DISABLE_RB11_OPENDRAIN() _ODCB11 = 0
#define ENABLE_RB12_OPENDRAIN() _ODCB12 = 1
#define DISABLE_RB12_OPENDRAIN() _ODCB12 = 0
#define ENABLE_RB13_OPENDRAIN() _ODCB13 = 1
#define DISABLE_RB13_OPENDRAIN() _ODCB13 = 0
#define ENABLE_RB14_OPENDRAIN() _ODCB14 = 1
#define DISABLE_RB14_OPENDRAIN() _ODCB14 = 0
#define ENABLE_RB15_OPENDRAIN() _ODCB15 = 1
#define DISABLE_RB15_OPENDRAIN() _ODCB15 = 0
#define ENABLE_RC0_OPENDRAIN() _ODCC0 = 1
#define DISABLE_RC0_OPENDRAIN() _ODCC0 = 0
#define ENABLE_RC1_OPENDRAIN() _ODCC1 = 1
#define DISABLE_RC1_OPENDRAIN() _ODCC1 = 0
#define ENABLE_RC2_OPENDRAIN() _ODCC2 = 1
#define DISABLE_RC2_OPENDRAIN() _ODCC2 = 0
#define ENABLE_RC3_OPENDRAIN() _ODCC3 = 1
#define DISABLE_RC3_OPENDRAIN() _ODCC3 = 0
#define ENABLE_RC4_OPENDRAIN() _ODCC4 = 1
#define DISABLE_RC4_OPENDRAIN() _ODCC4 = 0
#define ENABLE_RC5_OPENDRAIN() _ODCC5 = 1
#define DISABLE_RC5_OPENDRAIN() _ODCC5 = 0
#define ENABLE_RC6_OPENDRAIN() _ODCC6 = 1
#define DISABLE_RC6_OPENDRAIN() _ODCC6 = 0
#define ENABLE_RC7_OPENDRAIN() _ODCC7 = 1
#define DISABLE_RC7_OPENDRAIN() _ODCC7 = 0
#define ENABLE_RC8_OPENDRAIN() _ODCC8 = 1
#define DISABLE_RC8_OPENDRAIN() _ODCC8 = 0
#define ENABLE_RC9_OPENDRAIN() _ODCC9 = 1
#define DISABLE_RC9_OPENDRAIN() _ODCC9 = 0
#define ENABLE_RC10_OPENDRAIN() _ODCC10 = 1
#define DISABLE_RC10_OPENDRAIN() _ODCC10 = 0
#define ENABLE_RC11_OPENDRAIN() _ODCC11 = 1
#define DISABLE_RC11_OPENDRAIN() _ODCC11 = 0
#define ENABLE_RC12_OPENDRAIN() _ODCC12 = 1
#define DISABLE_RC12_OPENDRAIN() _ODCC12 = 0
#define ENABLE_RC13_OPENDRAIN() _ODCC13 = 1
#define DISABLE_RC13_OPENDRAIN() _ODCC13 = 0
#define ENABLE_RC15_OPENDRAIN() _ODCC15 = 1
#define DISABLE_RC15_OPENDRAIN() _ODCC15 = 0
#define ENABLE_RD5_OPENDRAIN() _ODCD5 = 1
#define DISABLE_RD5_OPENDRAIN() _ODCD5 = 0
#define ENABLE_RD6_OPENDRAIN() _ODCD6 = 1
#define DISABLE_RD6_OPENDRAIN() _ODCD6 = 0
#define ENABLE_RD8_OPENDRAIN() _ODCD8 = 1
#define DISABLE_RD8_OPENDRAIN() _ODCD8 = 0
#define ENABLE_RE12_OPENDRAIN() _ODCE12 = 1
#define DISABLE_RE12_OPENDRAIN() _ODCE12 = 0
#define ENABLE_RE13_OPENDRAIN() _ODCE13 = 1
#define DISABLE_RE13_OPENDRAIN() _ODCE13 = 0
#define ENABLE_RE14_OPENDRAIN() _ODCE14 = 1
#define DISABLE_RE14_OPENDRAIN() _ODCE14 = 0
#define ENABLE_RE15_OPENDRAIN() _ODCE15 = 1
#define DISABLE_RE15_OPENDRAIN() _ODCE15 = 0
#define ENABLE_RF0_OPENDRAIN() _ODCF0 = 1
#define DISABLE_RF0_OPENDRAIN() _ODCF0 = 0
#define ENABLE_RF1_OPENDRAIN() _ODCF1 = 1
#define DISABLE_RF1_OPENDRAIN() _ODCF1 = 0
#define ENABLE_RG6_OPENDRAIN() _ODCG6 = 1
#define DISABLE_RG6_OPENDRAIN() _ODCG6 = 0
#define ENABLE_RG7_OPENDRAIN() _ODCG7 = 1
#define DISABLE_RG7_OPENDRAIN() _ODCG7 = 0
#define ENABLE_RG8_OPENDRAIN() _ODCG8 = 1
#define DISABLE_RG8_OPENDRAIN() _ODCG8 = 0
#define ENABLE_RG9_OPENDRAIN() _ODCG9 = 1
#define DISABLE_RG9_OPENDRAIN() _ODCG9 = 0
static inline void CONFIG_RA0_AS_DIG_OUTPUT() {
  DISABLE_RA0_OPENDRAIN();
  _TRISA0 = 0;
  _ANSA0 = 1;
}
static inline void CONFIG_RA1_AS_DIG_OUTPUT() {
  DISABLE_RA1_OPENDRAIN();
  _TRISA1 = 0;
  _ANSA1 = 1;
}
static inline void CONFIG_RA4_AS_DIG_OUTPUT() {
  DISABLE_RA4_OPENDRAIN();
  _TRISA4 = 0;
}
static inline void CONFIG_RA8_AS_DIG_OUTPUT() {
  DISABLE_RA8_OPENDRAIN();
  _TRISA8 = 0;
}
static inline void CONFIG_RA9_AS_DIG_OUTPUT() {
  DISABLE_RA9_OPENDRAIN();
  _TRISA9 = 0;
}
static inline void CONFIG_RA10_AS_DIG_OUTPUT() {
  DISABLE_RA10_OPENDRAIN();
  _TRISA10 = 0;
}
static inline void CONFIG_RA11_AS_DIG_OUTPUT() {
  DISABLE_RA11_OPENDRAIN();
  _TRISA11 = 0;
  _ANSA11 = 1;
}
static inline void CONFIG_RA12_AS_DIG_OUTPUT() {
  DISABLE_RA12_OPENDRAIN();
  _TRISA12 = 0;
  _ANSA12 = 1;
}
static inline void CONFIG_RB0_AS_DIG_OUTPUT() {
  DISABLE_RB0_OPENDRAIN();
  _TRISB0 = 0;
  _ANSB0 = 1;
}
static inline void CONFIG_RB1_AS_DIG_OUTPUT() {
  DISABLE_RB1_OPENDRAIN();
  _TRISB1 = 0;
  _ANSB1 = 1;
}
static inline void CONFIG_RB2_AS_DIG_OUTPUT() {
  DISABLE_RB2_OPENDRAIN();
  _TRISB2 = 0;
  _ANSB2 = 1;
}
static inline void CONFIG_RB3_AS_DIG_OUTPUT() {
  DISABLE_RB3_OPENDRAIN();
  _TRISB3 = 0;
  _ANSB3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_OUTPUT() {
  DISABLE_RB4_OPENDRAIN();
  _TRISB4 = 0;
}
static inline void CONFIG_RB5_AS_DIG_OUTPUT() {
  DISABLE_RB5_OPENDRAIN();
  _TRISB5 = 0;
}
static inline void CONFIG_RB6_AS_DIG_OUTPUT() {
  DISABLE_RB6_OPENDRAIN();
  _TRISB6 = 0;
}
static inline void CONFIG_RB7_AS_DIG_OUTPUT() {
  DISABLE_RB7_OPENDRAIN();
  _TRISB7 = 0;
}
static inline void CONFIG_RB8_AS_DIG_OUTPUT() {
  DISABLE_RB8_OPENDRAIN();
  _TRISB8 = 0;
}
static inline void CONFIG_RB9_AS_DIG_OUTPUT() {
  DISABLE_RB9_OPENDRAIN();
  _TRISB9 = 0;
}
static inline void CONFIG_RB10_AS_DIG_OUTPUT() {
  DISABLE_RB10_OPENDRAIN();
  _TRISB10 = 0;
}
static inline void CONFIG_RB11_AS_DIG_OUTPUT() {
  DISABLE_RB11_OPENDRAIN();
  _TRISB11 = 0;
}
static inline void CONFIG_RB12_AS_DIG_OUTPUT() {
  DISABLE_RB12_OPENDRAIN();
  _TRISB12 = 0;
}
static inline void CONFIG_RB13_AS_DIG_OUTPUT() {
  DISABLE_RB13_OPENDRAIN();
  _TRISB13 = 0;
}
static inline void CONFIG_RB14_AS_DIG_OUTPUT() {
  DISABLE_RB14_OPENDRAIN();
  _TRISB14 = 0;
}
static inline void CONFIG_RB15_AS_DIG_OUTPUT() {
  DISABLE_RB15_OPENDRAIN();
  _TRISB15 = 0;
}
static inline void CONFIG_RC0_AS_DIG_OUTPUT() {
  DISABLE_RC0_OPENDRAIN();
  _TRISC0 = 0;
  _ANSC0 = 1;
}
static inline void CONFIG_RC1_AS_DIG_OUTPUT() {
  DISABLE_RC1_OPENDRAIN();
  _TRISC1 = 0;
  _ANSC1 = 1;
}
static inline void CONFIG_RC2_AS_DIG_OUTPUT() {
  DISABLE_RC2_OPENDRAIN();
  _TRISC2 = 0;
  _ANSC2 = 1;
}
static inline void CONFIG_RC3_AS_DIG_OUTPUT() {
  DISABLE_RC3_OPENDRAIN();
  _TRISC3 = 0;
}
static inline void CONFIG_RC4_AS_DIG_OUTPUT() {
  DISABLE_RC4_OPENDRAIN();
  _TRISC4 = 0;
}
static inline void CONFIG_RC5_AS_DIG_OUTPUT() {
  DISABLE_RC5_OPENDRAIN();
  _TRISC5 = 0;
}
static inline void CONFIG_RC6_AS_DIG_OUTPUT() {
  DISABLE_RC6_OPENDRAIN();
  _TRISC6 = 0;
}
static inline void CONFIG_RC7_AS_DIG_OUTPUT() {
  DISABLE_RC7_OPENDRAIN();
  _TRISC7 = 0;
}
static inline void CONFIG_RC8_AS_DIG_OUTPUT() {
  DISABLE_RC8_OPENDRAIN();
  _TRISC8 = 0;
}
static inline void CONFIG_RC9_AS_DIG_OUTPUT() {
  DISABLE_RC9_OPENDRAIN();
  _TRISC9 = 0;
}
static inline void CONFIG_RC10_AS_DIG_OUTPUT() {
  DISABLE_RC10_OPENDRAIN();
  _TRISC10 = 0;
}
static inline void CONFIG_RC11_AS_DIG_OUTPUT() {
  DISABLE_RC11_OPENDRAIN();
  _TRISC11 = 0;
  _ANSC11 = 1;
}
static inline void CONFIG_RC12_AS_DIG_OUTPUT() {
  DISABLE_RC12_OPENDRAIN();
  _TRISC12 = 0;
}
static inline void CONFIG_RC13_AS_DIG_OUTPUT() {
  DISABLE_RC13_OPENDRAIN();
  _TRISC13 = 0;
}
static inline void CONFIG_RC15_AS_DIG_OUTPUT() {
  DISABLE_RC15_OPENDRAIN();
  _TRISC15 = 0;
}
static inline void CONFIG_RD5_AS_DIG_OUTPUT() {
  DISABLE_RD5_OPENDRAIN();
  _TRISD5 = 0;
}
static inline void CONFIG_RD6_AS_DIG_OUTPUT() {
  DISABLE_RD6_OPENDRAIN();
  _TRISD6 = 0;
}
static inline void CONFIG_RD8_AS_DIG_OUTPUT() {
  DISABLE_RD8_OPENDRAIN();
  _TRISD8 = 0;
}
static inline void CONFIG_RE12_AS_DIG_OUTPUT() {
  DISABLE_RE12_OPENDRAIN();
  _TRISE12 = 0;
  _ANSE12 = 1;
}
static inline void CONFIG_RE13_AS_DIG_OUTPUT() {
  DISABLE_RE13_OPENDRAIN();
  _TRISE13 = 0;
  _ANSE13 = 1;
}
static inline void CONFIG_RE14_AS_DIG_OUTPUT() {
  DISABLE_RE14_OPENDRAIN();
  _TRISE14 = 0;
  _ANSE14 = 1;
}
static inline void CONFIG_RE15_AS_DIG_OUTPUT() {
  DISABLE_RE15_OPENDRAIN();
  _TRISE15 = 0;
  _ANSE15 = 1;
}
static inline void CONFIG_RF0_AS_DIG_OUTPUT() {
  DISABLE_RF0_OPENDRAIN();
  _TRISF0 = 0;
}
static inline void CONFIG_RF1_AS_DIG_OUTPUT() {
  DISABLE_RF1_OPENDRAIN();
  _TRISF1 = 0;
}
static inline void CONFIG_RG6_AS_DIG_OUTPUT() {
  DISABLE_RG6_OPENDRAIN();
  _TRISG6 = 0;
}
static inline void CONFIG_RG7_AS_DIG_OUTPUT() {
  DISABLE_RG7_OPENDRAIN();
  _TRISG7 = 0;
}
static inline void CONFIG_RG8_AS_DIG_OUTPUT() {
  DISABLE_RG8_OPENDRAIN();
  _TRISG8 = 0;
}
static inline void CONFIG_RG9_AS_DIG_OUTPUT() {
  DISABLE_RG9_OPENDRAIN();
  _TRISG9 = 0;
}
static inline void CONFIG_RA0_AS_DIG_OD_OUTPUT() {
  ENABLE_RA0_OPENDRAIN();
  _TRISA0 = 0;
  _ANSA0 = 1;
}
static inline void CONFIG_RA1_AS_DIG_OD_OUTPUT() {
  ENABLE_RA1_OPENDRAIN();
  _TRISA1 = 0;
  _ANSA1 = 1;
}
static inline void CONFIG_RA4_AS_DIG_OD_OUTPUT() {
  ENABLE_RA4_OPENDRAIN();
  _TRISA4 = 0;
}
static inline void CONFIG_RA8_AS_DIG_OD_OUTPUT() {
  ENABLE_RA8_OPENDRAIN();
  _TRISA8 = 0;
}
static inline void CONFIG_RA9_AS_DIG_OD_OUTPUT() {
  ENABLE_RA9_OPENDRAIN();
  _TRISA9 = 0;
}
static inline void CONFIG_RA10_AS_DIG_OD_OUTPUT() {
  ENABLE_RA10_OPENDRAIN();
  _TRISA10 = 0;
}
static inline void CONFIG_RA11_AS_DIG_OD_OUTPUT() {
  ENABLE_RA11_OPENDRAIN();
  _TRISA11 = 0;
  _ANSA11 = 1;
}
static inline void CONFIG_RA12_AS_DIG_OD_OUTPUT() {
  ENABLE_RA12_OPENDRAIN();
  _TRISA12 = 0;
  _ANSA12 = 1;
}
static inline void CONFIG_RB0_AS_DIG_OD_OUTPUT() {
  ENABLE_RB0_OPENDRAIN();
  _TRISB0 = 0;
  _ANSB0 = 1;
}
static inline void CONFIG_RB1_AS_DIG_OD_OUTPUT() {
  ENABLE_RB1_OPENDRAIN();
  _TRISB1 = 0;
  _ANSB1 = 1;
}
static inline void CONFIG_RB2_AS_DIG_OD_OUTPUT() {
  ENABLE_RB2_OPENDRAIN();
  _TRISB2 = 0;
  _ANSB2 = 1;
}
static inline void CONFIG_RB3_AS_DIG_OD_OUTPUT() {
  ENABLE_RB3_OPENDRAIN();
  _TRISB3 = 0;
  _ANSB3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_OD_OUTPUT() {
  ENABLE_RB4_OPENDRAIN();
  _TRISB4 = 0;
}
static inline void CONFIG_RB5_AS_DIG_OD_OUTPUT() {
  ENABLE_RB5_OPENDRAIN();
  _TRISB5 = 0;
}
static inline void CONFIG_RB6_AS_DIG_OD_OUTPUT() {
  ENABLE_RB6_OPENDRAIN();
  _TRISB6 = 0;
}
static inline void CONFIG_RB7_AS_DIG_OD_OUTPUT() {
  ENABLE_RB7_OPENDRAIN();
  _TRISB7 = 0;
}
static inline void CONFIG_RB8_AS_DIG_OD_OUTPUT() {
  ENABLE_RB8_OPENDRAIN();
  _TRISB8 = 0;
}
static inline void CONFIG_RB9_AS_DIG_OD_OUTPUT() {
  ENABLE_RB9_OPENDRAIN();
  _TRISB9 = 0;
}
static inline void CONFIG_RB10_AS_DIG_OD_OUTPUT() {
  ENABLE_RB10_OPENDRAIN();
  _TRISB10 = 0;
}
static inline void CONFIG_RB11_AS_DIG_OD_OUTPUT() {
  ENABLE_RB11_OPENDRAIN();
  _TRISB11 = 0;
}
static inline void CONFIG_RB12_AS_DIG_OD_OUTPUT() {
  ENABLE_RB12_OPENDRAIN();
  _TRISB12 = 0;
}
static inline void CONFIG_RB13_AS_DIG_OD_OUTPUT() {
  ENABLE_RB13_OPENDRAIN();
  _TRISB13 = 0;
}
static inline void CONFIG_RB14_AS_DIG_OD_OUTPUT() {
  ENABLE_RB14_OPENDRAIN();
  _TRISB14 = 0;
}
static inline void CONFIG_RB15_AS_DIG_OD_OUTPUT() {
  ENABLE_RB15_OPENDRAIN();
  _TRISB15 = 0;
}
static inline void CONFIG_RC0_AS_DIG_OD_OUTPUT() {
  ENABLE_RC0_OPENDRAIN();
  _TRISC0 = 0;
  _ANSC0 = 1;
}
static inline void CONFIG_RC1_AS_DIG_OD_OUTPUT() {
  ENABLE_RC1_OPENDRAIN();
  _TRISC1 = 0;
  _ANSC1 = 1;
}
static inline void CONFIG_RC2_AS_DIG_OD_OUTPUT() {
  ENABLE_RC2_OPENDRAIN();
  _TRISC2 = 0;
  _ANSC2 = 1;
}
static inline void CONFIG_RC3_AS_DIG_OD_OUTPUT() {
  ENABLE_RC3_OPENDRAIN();
  _TRISC3 = 0;
}
static inline void CONFIG_RC4_AS_DIG_OD_OUTPUT() {
  ENABLE_RC4_OPENDRAIN();
  _TRISC4 = 0;
}
static inline void CONFIG_RC5_AS_DIG_OD_OUTPUT() {
  ENABLE_RC5_OPENDRAIN();
  _TRISC5 = 0;
}
static inline void CONFIG_RC6_AS_DIG_OD_OUTPUT() {
  ENABLE_RC6_OPENDRAIN();
  _TRISC6 = 0;
}
static inline void CONFIG_RC7_AS_DIG_OD_OUTPUT() {
  ENABLE_RC7_OPENDRAIN();
  _TRISC7 = 0;
}
static inline void CONFIG_RC8_AS_DIG_OD_OUTPUT() {
  ENABLE_RC8_OPENDRAIN();
  _TRISC8 = 0;
}
static inline void CONFIG_RC9_AS_DIG_OD_OUTPUT() {
  ENABLE_RC9_OPENDRAIN();
  _TRISC9 = 0;
}
static inline void CONFIG_RC10_AS_DIG_OD_OUTPUT() {
  ENABLE_RC10_OPENDRAIN();
  _TRISC10 = 0;
}
static inline void CONFIG_RC11_AS_DIG_OD_OUTPUT() {
  ENABLE_RC11_OPENDRAIN();
  _TRISC11 = 0;
  _ANSC11 = 1;
}
static inline void CONFIG_RC12_AS_DIG_OD_OUTPUT() {
  ENABLE_RC12_OPENDRAIN();
  _TRISC12 = 0;
}
static inline void CONFIG_RC13_AS_DIG_OD_OUTPUT() {
  ENABLE_RC13_OPENDRAIN();
  _TRISC13 = 0;
}
static inline void CONFIG_RC15_AS_DIG_OD_OUTPUT() {
  ENABLE_RC15_OPENDRAIN();
  _TRISC15 = 0;
}
static inline void CONFIG_RD5_AS_DIG_OD_OUTPUT() {
  ENABLE_RD5_OPENDRAIN();
  _TRISD5 = 0;
}
static inline void CONFIG_RD6_AS_DIG_OD_OUTPUT() {
  ENABLE_RD6_OPENDRAIN();
  _TRISD6 = 0;
}
static inline void CONFIG_RD8_AS_DIG_OD_OUTPUT() {
  ENABLE_RD8_OPENDRAIN();
  _TRISD8 = 0;
}
static inline void CONFIG_RE12_AS_DIG_OD_OUTPUT() {
  ENABLE_RE12_OPENDRAIN();
  _TRISE12 = 0;
  _ANSE12 = 1;
}
static inline void CONFIG_RE13_AS_DIG_OD_OUTPUT() {
  ENABLE_RE13_OPENDRAIN();
  _TRISE13 = 0;
  _ANSE13 = 1;
}
static inline void CONFIG_RE14_AS_DIG_OD_OUTPUT() {
  ENABLE_RE14_OPENDRAIN();
  _TRISE14 = 0;
  _ANSE14 = 1;
}
static inline void CONFIG_RE15_AS_DIG_OD_OUTPUT() {
  ENABLE_RE15_OPENDRAIN();
  _TRISE15 = 0;
  _ANSE15 = 1;
}
static inline void CONFIG_RF0_AS_DIG_OD_OUTPUT() {
  ENABLE_RF0_OPENDRAIN();
  _TRISF0 = 0;
}
static inline void CONFIG_RF1_AS_DIG_OD_OUTPUT() {
  ENABLE_RF1_OPENDRAIN();
  _TRISF1 = 0;
}
static inline void CONFIG_RG6_AS_DIG_OD_OUTPUT() {
  ENABLE_RG6_OPENDRAIN();
  _TRISG6 = 0;
}
static inline void CONFIG_RG7_AS_DIG_OD_OUTPUT() {
  ENABLE_RG7_OPENDRAIN();
  _TRISG7 = 0;
}
static inline void CONFIG_RG8_AS_DIG_OD_OUTPUT() {
  ENABLE_RG8_OPENDRAIN();
  _TRISG8 = 0;
}
static inline void CONFIG_RG9_AS_DIG_OD_OUTPUT() {
  ENABLE_RG9_OPENDRAIN();
  _TRISG9 = 0;
}
static inline void CONFIG_RA0_AS_DIG_INPUT() {
  _TRISA0 = 1;
  _ANSA0 = 1;
}
static inline void CONFIG_RA1_AS_DIG_INPUT() {
  _TRISA1 = 1;
  _ANSA1 = 1;
}
static inline void CONFIG_RA4_AS_DIG_INPUT() {
  _TRISA4 = 1;
}
static inline void CONFIG_RA8_AS_DIG_INPUT() {
  _TRISA8 = 1;
}
static inline void CONFIG_RA9_AS_DIG_INPUT() {
  _TRISA9 = 1;
}
static inline void CONFIG_RA10_AS_DIG_INPUT() {
  _TRISA10 = 1;
}
static inline void CONFIG_RA11_AS_DIG_INPUT() {
  _TRISA11 = 1;
  _ANSA11 = 1;
}
static inline void CONFIG_RA12_AS_DIG_INPUT() {
  _TRISA12 = 1;
  _ANSA12 = 1;
}
static inline void CONFIG_RB0_AS_DIG_INPUT() {
  _TRISB0 = 1;
  _ANSB0 = 1;
}
static inline void CONFIG_RB1_AS_DIG_INPUT() {
  _TRISB1 = 1;
  _ANSB1 = 1;
}
static inline void CONFIG_RB2_AS_DIG_INPUT() {
  _TRISB2 = 1;
  _ANSB2 = 1;
}
static inline void CONFIG_RB3_AS_DIG_INPUT() {
  _TRISB3 = 1;
  _ANSB3 = 1;
}
static inline void CONFIG_RB4_AS_DIG_INPUT() {
  _TRISB4 = 1;
}
static inline void CONFIG_RB5_AS_DIG_INPUT() {
  _TRISB5 = 1;
}
static inline void CONFIG_RB6_AS_DIG_INPUT() {
  _TRISB6 = 1;
}
static inline void CONFIG_RB7_AS_DIG_INPUT() {
  _TRISB7 = 1;
}
static inline void CONFIG_RB8_AS_DIG_INPUT() {
  _TRISB8 = 1;
}
static inline void CONFIG_RB9_AS_DIG_INPUT() {
  _TRISB9 = 1;
}
static inline void CONFIG_RB10_AS_DIG_INPUT() {
  _TRISB10 = 1;
}
static inline void CONFIG_RB11_AS_DIG_INPUT() {
  _TRISB11 = 1;
}
static inline void CONFIG_RB12_AS_DIG_INPUT() {
  _TRISB12 = 1;
}
static inline void CONFIG_RB13_AS_DIG_INPUT() {
  _TRISB13 = 1;
}
static inline void CONFIG_RB14_AS_DIG_INPUT() {
  _TRISB14 = 1;
}
static inline void CONFIG_RB15_AS_DIG_INPUT() {
  _TRISB15 = 1;
}
static inline void CONFIG_RC0_AS_DIG_INPUT() {
  _TRISC0 = 1;
  _ANSC0 = 1;
}
static inline void CONFIG_RC1_AS_DIG_INPUT() {
  _TRISC1 = 1;
  _ANSC1 = 1;
}
static inline void CONFIG_RC2_AS_DIG_INPUT() {
  _TRISC2 = 1;
  _ANSC2 = 1;
}
static inline void CONFIG_RC3_AS_DIG_INPUT() {
  _TRISC3 = 1;
}
static inline void CONFIG_RC4_AS_DIG_INPUT() {
  _TRISC4 = 1;
}
static inline void CONFIG_RC5_AS_DIG_INPUT() {
  _TRISC5 = 1;
}
static inline void CONFIG_RC6_AS_DIG_INPUT() {
  _TRISC6 = 1;
}
static inline void CONFIG_RC7_AS_DIG_INPUT() {
  _TRISC7 = 1;
}
static inline void CONFIG_RC8_AS_DIG_INPUT() {
  _TRISC8 = 1;
}
static inline void CONFIG_RC9_AS_DIG_INPUT() {
  _TRISC9 = 1;
}
static inline void CONFIG_RC10_AS_DIG_INPUT() {
  _TRISC10 = 1;
}
static inline void CONFIG_RC11_AS_DIG_INPUT() {
  _TRISC11 = 1;
  _ANSC11 = 1;
}
static inline void CONFIG_RC12_AS_DIG_INPUT() {
  _TRISC12 = 1;
}
static inline void CONFIG_RC13_AS_DIG_INPUT() {
  _TRISC13 = 1;
}
static inline void CONFIG_RC15_AS_DIG_INPUT() {
  _TRISC15 = 1;
}
static inline void CONFIG_RD5_AS_DIG_INPUT() {
  _TRISD5 = 1;
}
static inline void CONFIG_RD6_AS_DIG_INPUT() {
  _TRISD6 = 1;
}
static inline void CONFIG_RD8_AS_DIG_INPUT() {
  _TRISD8 = 1;
}
static inline void CONFIG_RE12_AS_DIG_INPUT() {
  _TRISE12 = 1;
  _ANSE12 = 1;
}
static inline void CONFIG_RE13_AS_DIG_INPUT() {
  _TRISE13 = 1;
  _ANSE13 = 1;
}
static inline void CONFIG_RE14_AS_DIG_INPUT() {
  _TRISE14 = 1;
  _ANSE14 = 1;
}
static inline void CONFIG_RE15_AS_DIG_INPUT() {
  _TRISE15 = 1;
  _ANSE15 = 1;
}
static inline void CONFIG_RF0_AS_DIG_INPUT() {
  _TRISF0 = 1;
}
static inline void CONFIG_RF1_AS_DIG_INPUT() {
  _TRISF1 = 1;
}
static inline void CONFIG_RG6_AS_DIG_INPUT() {
  _TRISG6 = 1;
}
static inline void CONFIG_RG7_AS_DIG_INPUT() {
  _TRISG7 = 1;
}
static inline void CONFIG_RG8_AS_DIG_INPUT() {
  _TRISG8 = 1;
}
static inline void CONFIG_RG9_AS_DIG_INPUT() {
  _TRISG9 = 1;
}
#define CONFIG_RP0_AS_DIG_PIN()
#define CONFIG_RP1_AS_DIG_PIN()
#define CONFIG_RP2_AS_DIG_PIN()
#define CONFIG_RP3_AS_DIG_PIN()
#define CONFIG_RP4_AS_DIG_PIN()
#define CONFIG_RP5_AS_DIG_PIN()
#define CONFIG_RP6_AS_DIG_PIN()
#define CONFIG_RP7_AS_DIG_PIN()
#define CONFIG_RP8_AS_DIG_PIN()
#define CONFIG_RP9_AS_DIG_PIN()
#define CONFIG_RP10_AS_DIG_PIN()
#define CONFIG_RP11_AS_DIG_PIN()
#define CONFIG_RP12_AS_DIG_PIN()
#define CONFIG_RP13_AS_DIG_PIN()
#define CONFIG_RP14_AS_DIG_PIN()
#define CONFIG_RP15_AS_DIG_PIN()
#define CONFIG_RP16_AS_DIG_PIN()
#define CONFIG_RP17_AS_DIG_PIN()
#define CONFIG_RP18_AS_DIG_PIN()
#define CONFIG_RP19_AS_DIG_PIN()
#define CONFIG_RP20_AS_DIG_PIN()
#define CONFIG_RP21_AS_DIG_PIN()
#define CONFIG_RP22_AS_DIG_PIN()
#define CONFIG_RP23_AS_DIG_PIN()
#define CONFIG_RP24_AS_DIG_PIN()
#define CONFIG_RP25_AS_DIG_PIN()
#define CONFIG_RP26_AS_DIG_PIN()
#define CONFIG_RP27_AS_DIG_PIN()  _ANSA11 = 1
#define CONFIG_RP28_AS_DIG_PIN()  _ANSA12 = 1
#define CONFIG_RP29_AS_DIG_PIN()
#define CONFIG_RP30_AS_DIG_PIN()
#define CONFIG_RP31_AS_DIG_PIN()
#define CONFIG_RP32_AS_DIG_PIN()  _ANSB0 = 1
#define CONFIG_RP33_AS_DIG_PIN()  _ANSB1 = 1
#define CONFIG_RP34_AS_DIG_PIN()  _ANSB2 = 1
#define CONFIG_RP35_AS_DIG_PIN()  _ANSB3 = 1
#define CONFIG_RP36_AS_DIG_PIN()
#define CONFIG_RP37_AS_DIG_PIN()
#define CONFIG_RP38_AS_DIG_PIN()
#define CONFIG_RP39_AS_DIG_PIN()
#define CONFIG_RP40_AS_DIG_PIN()
#define CONFIG_RP41_AS_DIG_PIN()
#define CONFIG_RP42_AS_DIG_PIN()
#define CONFIG_RP43_AS_DIG_PIN()
#define CONFIG_RP44_AS_DIG_PIN()
#define CONFIG_RP45_AS_DIG_PIN()
#define CONFIG_RP46_AS_DIG_PIN()
#define CONFIG_RP47_AS_DIG_PIN()
#define CONFIG_RP48_AS_DIG_PIN()
#define CONFIG_RP49_AS_DIG_PIN()
#define CONFIG_RP50_AS_DIG_PIN()
#define CONFIG_RP51_AS_DIG_PIN()
#define CONFIG_RP52_AS_DIG_PIN()
#define CONFIG_RP53_AS_DIG_PIN()
#define CONFIG_RP54_AS_DIG_PIN()
#define CONFIG_RP55_AS_DIG_PIN()
#define CONFIG_RP56_AS_DIG_PIN()
#define CONFIG_RP57_AS_DIG_PIN()
#define CONFIG_RP58_AS_DIG_PIN()
#define CONFIG_RP59_AS_DIG_PIN()
#define CONFIG_RP60_AS_DIG_PIN()
#define CONFIG_RP61_AS_DIG_PIN()
#define CONFIG_RP62_AS_DIG_PIN()
#define CONFIG_RP63_AS_DIG_PIN()
#define CONFIG_RP64_AS_DIG_PIN()
#define CONFIG_RP65_AS_DIG_PIN()
#define CONFIG_RP66_AS_DIG_PIN()
#define CONFIG_RP67_AS_DIG_PIN()
#define CONFIG_RP68_AS_DIG_PIN()
#define CONFIG_RP69_AS_DIG_PIN()
#define CONFIG_RP70_AS_DIG_PIN()
#define CONFIG_RP71_AS_DIG_PIN()
#define CONFIG_RP72_AS_DIG_PIN()
#define CONFIG_RP73_AS_DIG_PIN()
#define CONFIG_RP74_AS_DIG_PIN()
#define CONFIG_RP75_AS_DIG_PIN()
#define CONFIG_RP76_AS_DIG_PIN()
#define CONFIG_RP77_AS_DIG_PIN()
#define CONFIG_RP78_AS_DIG_PIN()
#define CONFIG_RP79_AS_DIG_PIN()
#define CONFIG_RP80_AS_DIG_PIN()
#define CONFIG_RP81_AS_DIG_PIN()
#define CONFIG_RP82_AS_DIG_PIN()
#define CONFIG_RP83_AS_DIG_PIN()
#define CONFIG_RP84_AS_DIG_PIN()
#define CONFIG_RP85_AS_DIG_PIN()
#define CONFIG_RP86_AS_DIG_PIN()
#define CONFIG_RP87_AS_DIG_PIN()
#define CONFIG_RP88_AS_DIG_PIN()
#define CONFIG_RP89_AS_DIG_PIN()
#define CONFIG_RP90_AS_DIG_PIN()
#define CONFIG_RP91_AS_DIG_PIN()
#define CONFIG_RP92_AS_DIG_PIN()
#define CONFIG_RP93_AS_DIG_PIN()
#define CONFIG_RP94_AS_DIG_PIN()  _ANSE14 = 1
#define CONFIG_RP95_AS_DIG_PIN()  _ANSE15 = 1
#define CONFIG_RP96_AS_DIG_PIN()
#define CONFIG_RP97_AS_DIG_PIN()
#define CONFIG_RP98_AS_DIG_PIN()
#define CONFIG_RP99_AS_DIG_PIN()
#define DISABLE_C2IND_ANALOG()
#define DISABLE_U2CTS_ANALOG()
#define DISABLE_CTPLS_ANALOG()
#define DISABLE_U4TX_ANALOG()
#define DISABLE_SS2_ANALOG()
#define DISABLE_U3TX_ANALOG()
#define DISABLE_C1OUT_ANALOG()
#define DISABLE_INT1_ANALOG()
#define DISABLE_U1RTS_ANALOG()
#define DISABLE_T5CK_ANALOG()
#define DISABLE_C1IND_ANALOG()
#define DISABLE_U3CTS_ANALOG()
#define DISABLE_OC5_ANALOG()
#define DISABLE_U2TX_ANALOG()
#define DISABLE_C2INA_ANALOG()
#define DISABLE_INT0_ANALOG()
#define DISABLE_U1BCLK_ANALOG()
#define DISABLE_SS1_ANALOG()
#define DISABLE_IC4_ANALOG()
#define DISABLE_OCFB_ANALOG()
#define DISABLE_C1TX_ANALOG()
#define DISABLE_RTCC_ANALOG()
#define DISABLE_IC3_ANALOG()
#define DISABLE_T3CK_ANALOG()
#define DISABLE_C2OUT_ANALOG()
#define DISABLE_INT2_ANALOG()
#define DISABLE_OCFA_ANALOG()
#define DISABLE_OC4_ANALOG()
#define DISABLE_U1RX_ANALOG()
#define DISABLE_IC8_ANALOG()
#define DISABLE_U3RX_ANALOG()
#define DISABLE_CTED2_ANALOG()
#define DISABLE_IC1_ANALOG()
#define DISABLE_U2BCLK_ANALOG()
#define DISABLE_C1INA_ANALOG()
#define DISABLE_T4CK_ANALOG()
#define DISABLE_C2INC_ANALOG()
#define DISABLE_IC7_ANALOG()
#define DISABLE_IC2_ANALOG()
#define DISABLE_U2RTS_ANALOG()
#define DISABLE_U4RTS_ANALOG()
#define DISABLE_SDI2_ANALOG()
#define DISABLE_OC2_ANALOG()
#define DISABLE_C1RX_ANALOG()
#define DISABLE_C2RX_ANALOG()
#define DISABLE_SDO1_ANALOG()
#define DISABLE_U1CTS_ANALOG()
#define DISABLE_OC3_ANALOG()
#define DISABLE_C21INB_ANALOG()
#define DISABLE_U1TX_ANALOG()
#define DISABLE_T1CK_ANALOG()
#define DISABLE_SCK1_ANALOG()
#define DISABLE_U2RX_ANALOG()
#define DISABLE_T2CK_ANALOG()
#define DISABLE_CTED1_ANALOG()
#define DISABLE_U3RTS_ANALOG()
#define DISABLE_SDO2_ANALOG()
#define DISABLE_C1INC_ANALOG()
#define DISABLE_U4RX_ANALOG()
#define DISABLE_IC5_ANALOG()
#define DISABLE_SDI1_ANALOG()
#define DISABLE_C1INB_ANALOG()
#define DISABLE_OC1_ANALOG()
#define DISABLE_SCK2_ANALOG()
#define DISABLE_IC6_ANALOG()
#define DISABLE_U4CTS_ANALOG()
#define _PIC24_DIGIO_DEFINED
